CREATE TABLE IF NOT EXISTS inventory.data_daily (
    id                      BIGINT          NOT NULL,
    seller_id               INT             NOT NULL,
    site_id                 INT             NOT NULL,
    sku                     VARCHAR(255)    NOT NULL,
    seller_sku              VARCHAR(255)    NOT NULL,
    planning_min_stock      DOUBLE          NULL        DEFAULT NULL,
    daily_sale              DOUBLE          NULL        DEFAULT NULL,
    total_daily_sale        DOUBLE          NULL        DEFAULT NULL,
    forecast_daily_sale     DOUBLE          NULL        DEFAULT NULL,
    total_forecast_daily_sale DOUBLE        NULL        DEFAULT NULL,
    reorder_point           DOUBLE          NULL        DEFAULT NULL,
    lead_day                DOUBLE          NULL        DEFAULT NULL,
    available_qty           DOUBLE          NULL        DEFAULT NULL,
    reason                  TEXT            NULL        DEFAULT NULL,
    created_at              DATETIME(3)     NOT NULL    DEFAULT '1970-01-01 00:00:00.000',
    updated_at              DATETIME(3)     NOT NULL    DEFAULT '1970-01-01 00:00:00.000',
    created_by_id           VARCHAR(255)    NOT NULL,
    updated_by_id           VARCHAR(255)    NOT NULL,
    stock_days              DOUBLE          NULL        DEFAULT NULL,

    PRIMARY KEY (id)
);

INSERT INTO inventory.data_daily (
    id,
    seller_id,
    site_id,
    sku,
    seller_sku,
    planning_min_stock,
    daily_sale,
    total_daily_sale,
    forecast_daily_sale,
    total_forecast_daily_sale,
    reorder_point,
    lead_day,
    available_qty,
    reason,
    created_at,
    updated_at,
    created_by_id,
    updated_by_id,
    stock_days
) VALUES
(
    1,
    1001,
    1,
    'SKU-IPHONE-15',
    NULL,
    50.0,
    NULL,
    375.0,
    14.2,
    NULL,
    80.0,
    5.0,
    NULL,
    'Normal replenishment',
    NOW(6),
    NOW(6),
    'system',
    'system',
    NULL
),
(
    2,
    1002,
    1,
    NULL,
    'MBA-M2-256',
    NULL,
    3.1,
    NULL,
    NULL,
    120.0,
    25.0,
    NULL,
    18.0,
    NULL,
    NOW(6),
    NOW(6),
    'planner_bot',
    'planner_bot',
    5.8
),
(
    3,
    1003,
    2,
    'SKU-AIRPODS-PRO',
    'APPRO2-WHITE',
    100.0,
    25.0,
    NULL,
    28.5,
    855.0,
    NULL,
    3.0,
    320.0,
    NULL,
    NOW(6),
    NULL,
    'admin',
    'admin',
    12.8
);
